import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="w-[90%] max-w-7xl mx-auto">
          <nav className="py-8">Nav placeholder</nav>
          {children}
        </div>
      </body>
    </html>
  );
}
