// Library
import Providers from "@/app/lib/query-provider";

// Component
import Nav from "@/components/nav/nav";
import { Toaster } from "@/components/ui/toaster";

// Style
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="mx-auto w-[90%] max-w-7xl">
          <Providers>
            <Nav>{children}</Nav>
            <Toaster />
          </Providers>
        </div>
      </body>
    </html>
  );
}
